### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by szos** [dbjergaard/stumpwm-freetype-fonts#1]
I recently found this project, and would love to have a different font renderer from clx-truetype. However it seems this project isnt quite ready for primetime. Is this project active and should I open issues here, or would I be better served forking and trying to fix the issues myself (or looking for a different renderer)? I like this project, it renders things much better than clx-truetype, but I have other issues related to glyph size and spacing, as well as related to color inversion in StumpWM.

**Comment by dmb2** [comment]
Please! It was my dream that this would be the default font rendering engine for stumpwm.  Over time, I just wanted it to be a contrib module.  Then I couldn't even manage to get it running well enough for myself.  I got busy with other things, and then as life happens, I haven't been able to come back to it.

If you have any help for any of the issues you point out, I'm happy to get them merged, use them, and get this moved to stumpwm contrib proper :)

**Comment by szos** [comment]
Im glad to hear this isnt abandoned! Ill open up issues for the problems ive had, and start familiarizing myself with the codebase. Hopefully i can start writing patches soon-ish. One thing that would be very useful which i dont feel qualified to do quite yet is to fill out the readme with information about the project.

**Comment by szos** [comment]
I've left some PRs in this and clx-ft2-renderer, and I'm going to close this issue as it seems this project is very much alive.
